### PR TITLE
Add travis

### PR DESCRIPTION
**Pull request by domoritz**

### CODE REVIEW

**Comment by domoritz** [comment]
Looks like there are some issues with the generated png images. @jheer do the test pass on your computer? What version of node are you using?

**Comment by jheer** [comment]
I use node v6. It is not surprising that the PNG tests fail on Travis. Different versions of libcairo or related libraries behind `node-canvas` may be driving the observed errors. I'm going to go ahead and close this for now in lieu of local tests, but it could be valuable to return to this later (e.g., standardizing on specific versions of backing native libraries?) in the process of sorting out known issues with node 7.

**Comment by domoritz** [comment]
FWIW, the tests fail on travis even with node v6.

**Comment by jheer** [comment]
Yes I know. See comment above.

**Pull request closed without merging**
