### PR TITLE
Add viewBox attribute to SVGs

### PR DESCRIPTION
**Pull request by domoritz**
This allows us to set the width of an svg image and automatically scale the content.

### CODE REVIEW

**Comment by jheer** [comment]
Thanks! But what about `SVGStringRenderer`? And updated test cases?

**Comment by domoritz** [comment]
Is this something we want? If sounds like we do so I'll update the pr.

**Comment by domoritz** [comment]
Updated. @jheer I had a few test failures due to node 7 but it looks like the test should pass on node 6. I'm trying to add travis on a different branch.

**Comment by jheer** [comment]
Tests pass locally (node v6) without issue.

**Pull request merged**
